apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-gitlab
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/playground.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
