replicaCount: 1

image:
  rootless: true

persistence:
  enabled: true
  size: 5Gi

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: gitea.localhost
      paths:
        - path: /
          pathType: Prefix

gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    server:
      DOMAIN: gitea.localhost
      ROOT_URL: http://gitea.localhost:8081/
      HTTP_PORT: 3000
      SSH_DOMAIN: gitea.localhost
      DISABLE_SSH: true
    database:
      DB_TYPE: sqlite3
    cache:
      ADAPTER: memory
    session:
      PROVIDER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: false
    service:
      DISABLE_REGISTRATION: true

postgresql-ha:
  enabled: false
postgresql:
  enabled: false
redis-cluster:
  enabled: false
redis:
  enabled: false
valkey-cluster:
  enabled: false
valkey:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
