Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Common provisioning for all VMs
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
  SHELL

  # Server node
  config.vm.define "yelhadrS", primary: true do |yelhadrS|
    yelhadrS.vm.hostname = "yelhadrS"
    yelhadrS.vm.network "private_network", ip: "192.168.56.110"

    yelhadrS.vm.provider "virtualbox" do |vb|
      vb.name = "yelhadrS"
      vb.memory = 1024
      vb.cpus = 1
    end

    yelhadrS.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # Worker node
  config.vm.define "yelhadrSW" do |yelhadrSW|
    yelhadrSW.vm.hostname = "yelhadrSW"
    yelhadrSW.vm.network "private_network", ip: "192.168.56.111"

    yelhadrSW.vm.provider "virtualbox" do |vb|
      vb.name = "yelhadrSW"
      vb.memory = 1024
      vb.cpus = 1
    end

    yelhadrSW.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end