Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update -y
    sudo apt-get install -y curl
  SHELL

  config.vm.synced_folder ".", "/vagrant", disabled: true # Disable default synced folder

  config.vm.define "yelhadrS" ,  primary: true do |yelhadrS|
    yelhadrS.vm.hostname = "yelhadrS"
    yelhadrS.vm.network "private_network", ip: "192.168.56.110"

    yelhadrS.vm.provider "virtualbox" do |vb|
      vb.name = "yelhadrS"
      vb.memory = 2048
      vb.cpus = 2
    end
    yelhadrS.vm.provision "shell", path: "scripts/setup_server.sh"

  end

  config.vm.define "yelhadrSW" do |yelhadrSW|
    yelhadrSW.vm.hostname = "yelhadrSW"
    yelhadrSW.vm.network "private_network", ip: "192.168.56.111"

    yelhadrSW.vm.provider "virtualbox" do |vb|
      vb.name = "yelhadrSW"
      vb.memory = 2048
      vb.cpus = 2
    end
    yelhadrSW.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
